# SPDX-License-Identifier: MIT
# Copyright (c) 2026 The Jaxility Authors

"""Generate + run a benchmark binary for an acados controller (T-035).

The benchmark is the controller closed loop (acados OCP control + acados sim
plant, the T-034 shape) instrumented to time the bare `acados_solve` each cycle
with `CLOCK_MONOTONIC` — the quantity that must fit inside the control period.
Warm-up cycles are run untimed first (RTI warm-start settles), then `n_cycles`
are measured; the binary emits one JSON object with the per-cycle solve times
and the process peak RSS. :func:`run_controller_bench` runs it through a
:class:`jaxility.hil.TargetRunner` (``SshRunner`` for the Pi) and folds the
result into a :class:`jaxility.bench.BenchRecord`.

The binary is built with the same acados-linking recipe as the HIL binary
(:func:`jaxility.hil.controller.build_controller_hil_binary`); only the emitted
source differs (timing instead of a state trace).
"""

from __future__ import annotations

import json

from ..errors import BenchmarkError
from ..hil.runner import TargetRunner
from .record import BenchRecord


def generate_controller_bench_source(
    *,
    model_name: str,
    nx: int,
    nu: int,
    initial_state: tuple[float, ...],
    n_warmup: int = 100,
    seed_index: int = 0,
    seed_step: float = 0.01,
) -> str:
    """Emit the benchmark ``main`` C source for the acados controller ``model_name``.

    The generated program takes ``<n_cycles> <seed>`` argv, runs ``n_warmup``
    untimed cycles then ``n_cycles`` timed cycles of the closed loop, and writes
    ``{"solve_ns": [...], "max_rss_kib": N}`` to stdout.
    """
    if len(initial_state) != nx:
        raise BenchmarkError(
            f"initial_state has {len(initial_state)} entries; model {model_name!r} "
            f"has nx={nx}."
        )
    x0_init = ", ".join(repr(float(v)) for v in initial_state)
    return f"""\
/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 The Jaxility Authors
 *
 * GENERATED by jaxility.bench.controller_bench (T-035) — do not edit by hand.
 *
 * Benchmarks the acados controller {model_name!r}: times the bare solve each
 * cycle (CLOCK_MONOTONIC), after {n_warmup} warm-up cycles, advancing the
 * acados sim plant between cycles so the solve sees a realistic warm-started
 * trajectory. Emits one JSON timing record.
 */
#define _POSIX_C_SOURCE 200809L  /* clock_gettime on glibc */
#define _DARWIN_C_SOURCE 1       /* re-expose BSD struct rusage on macOS host */
#include "acados_solver_{model_name}.h"
#include "acados_sim_solver_{model_name}.h"
#include "acados_c/ocp_nlp_interface.h"
#include "acados_c/sim_interface.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/resource.h>

#define JX_NX {nx}
#define JX_NU {nu}
#define JX_N_WARMUP {n_warmup}L

static long now_ns(void) {{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long)ts.tv_sec * 1000000000L + (long)ts.tv_nsec;
}}

int main(int argc, char **argv) {{
    if (argc != 3) {{
        fprintf(stderr, "usage: %s <n_cycles> <seed>\\n", argv[0]);
        return 2;
    }}
    long n_cycles = strtol(argv[1], NULL, 10);
    long seed = strtol(argv[2], NULL, 10);
    if (n_cycles < 1 || n_cycles > 100000) {{
        fprintf(stderr, "n_cycles out of range [1, 100000]: %ld\\n", n_cycles);
        return 2;
    }}

    {model_name}_solver_capsule *ocp = {model_name}_acados_create_capsule();
    if (ocp == NULL || {model_name}_acados_create(ocp) != 0) {{
        fprintf(stderr, "acados OCP create failed\\n");
        return 1;
    }}
    ocp_nlp_config *cfg = {model_name}_acados_get_nlp_config(ocp);
    ocp_nlp_dims *dims = {model_name}_acados_get_nlp_dims(ocp);
    ocp_nlp_in *in = {model_name}_acados_get_nlp_in(ocp);
    ocp_nlp_out *out = {model_name}_acados_get_nlp_out(ocp);

    {model_name}_sim_solver_capsule *sim =
        {model_name}_acados_sim_solver_create_capsule();
    if (sim == NULL || {model_name}_acados_sim_create(sim) != 0) {{
        fprintf(stderr, "acados sim create failed\\n");
        return 1;
    }}
    sim_config *scfg = {model_name}_acados_get_sim_config(sim);
    void *sdims = {model_name}_acados_get_sim_dims(sim);
    sim_in *sin = {model_name}_acados_get_sim_in(sim);
    sim_out *sout = {model_name}_acados_get_sim_out(sim);

    double x[JX_NX] = {{{x0_init}}};
    double u[JX_NU];
    x[{seed_index}] += {seed_step!r} * (double)seed;

    long *samples = malloc((size_t)n_cycles * sizeof(long));
    if (samples == NULL) {{ fprintf(stderr, "oom\\n"); return 1; }}

    for (long i = 0; i < JX_N_WARMUP + n_cycles; ++i) {{
        ocp_nlp_constraints_model_set(cfg, dims, in, out, 0, "lbx", x);
        ocp_nlp_constraints_model_set(cfg, dims, in, out, 0, "ubx", x);
        long t0 = now_ns();
        int st = {model_name}_acados_solve(ocp);
        long t1 = now_ns();
        if (st != 0) {{
            fprintf(stderr, "acados solve failed at step %ld\\n", i);
            return 1;
        }}
        if (i >= JX_N_WARMUP) {{
            samples[i - JX_N_WARMUP] = t1 - t0;
        }}
        ocp_nlp_out_get(cfg, dims, out, 0, "u", u);
        sim_in_set(scfg, sdims, sin, "x", x);
        sim_in_set(scfg, sdims, sin, "u", u);
        if ({model_name}_acados_sim_solve(sim) != 0) {{
            fprintf(stderr, "acados sim solve failed at step %ld\\n", i);
            return 1;
        }}
        sim_out_get(scfg, sdims, sout, "xn", x);
    }}

    struct rusage ru;
    getrusage(RUSAGE_SELF, &ru);  /* ru_maxrss is KiB on Linux */

    printf("{{\\"solve_ns\\": [");
    for (long i = 0; i < n_cycles; ++i) {{
        printf("%ld%s", samples[i], (i + 1 < n_cycles) ? ", " : "");
    }}
    printf("], \\"max_rss_kib\\": %ld}}\\n", (long)ru.ru_maxrss);
    free(samples);
    return 0;
}}
"""


def run_controller_bench(
    runner: TargetRunner,
    *,
    robot: str,
    target_family: str,
    target_name: str,
    n_cycles: int,
    n_warmup: int,
    seed: int = 0,
    source_manifest_hash: str | None = None,
) -> BenchRecord:
    """Run the benchmark binary via ``runner`` and assemble a :class:`BenchRecord`.

    Raises
    ------
    BenchmarkError
        On a transport failure or a malformed timing record.
    """
    raw = runner.run(n_steps=n_cycles, seed=seed)
    try:
        record = json.loads(raw.strip().splitlines()[-1])
        solve_ns = [float(v) for v in record["solve_ns"]]
        max_rss_kib = int(record["max_rss_kib"])
    except (json.JSONDecodeError, KeyError, IndexError, ValueError, TypeError) as exc:
        raise BenchmarkError(
            f"benchmark target emitted a malformed timing record: {raw[:200]!r} "
            f"({exc})."
        ) from exc
    if len(solve_ns) != n_cycles:
        raise BenchmarkError(
            f"benchmark recorded {len(solve_ns)} samples; expected {n_cycles}."
        )
    return BenchRecord.from_solve_times(
        solve_ns,
        robot=robot,
        target_family=target_family,
        target_name=target_name,
        runner_label=runner.label,
        n_warmup=n_warmup,
        max_rss_kib=max_rss_kib,
        source_manifest_hash=source_manifest_hash,
    )
